export { default as About } from "./About";
export { default as Advantages } from "./Advantages";
export { default as BannerSection } from "./BannerSection";
export { default as Feedback } from "./Feedback";
export { default as Footer } from "./Footer";
export { default as MainHeader } from "./MainHeader";
export { default as PageContent } from "./PageContent";
export { default as PageHeader } from "./PageHeader";
export { default as Services } from "./Services";
